from . import cnn1
from . import cnn2
from . import cnn3
from . import cnn3_reg
from . import cnn4
from . import cnn5
from . import cnn6
from . import cnn8
from . import cnn9
from . import cnn10
from . import cnn11
from . import cnn12
from . import cnn13
from . import cnn14
from . import cnn15
from . import unet1
from . import unet2
from . import unet3
from . import unet4
from . import unet5
from . import unet6
from . import unet7
from . import unet8